### ISSUE TITLE
Pico_timer.py missing

### ISSUE THREAD

**Issue by gregoryng** [jbentham/picofreq#1]
In your blog post, you refer to this file (for measuring frequency using the reciprocal method), but I don't see it in the main branch of the repository. Thanks for the great post.

**Comment by tanant** [comment]
@gregoryng - in the clone i just took now, there's https://github.com/jbentham/picofreq/blob/main/pico_timer.py in main, is that what you're looking for?

**Comment by gregoryng** [comment]
Yes, that is what I was looking for and I guess it was there all along.

I was originally browsing on mobile and I see now that github only shows the first few entries unless you click "view more" so maybe that's what happened -- me not noticing that in the web site.
